export h="$HOME"
export XDG_CONFIG_HOME="$h/.config"
export XDG_DATA_HOME="$h/.local/share"
export XDG_BIN_HOME="$h/bin"
export plan9="/usr/local/p9p"
export LD_LIBRARY_PATH=/usr/local/lib
export GOPATH="$h/go"
export PATH="$XDG_BIN_HOME:$XDG_BIN_HOME/android-studio/bin:$h/ma:$GOPATH/bin:$h/.cargo/bin:$h/.local/kitty.app/bin:$h/.scripts:$h/.fzf/bin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin/el:/usr/local/games:/opt/libjpeg-turbo/bin:/snap/bin:/usr/lib/ncurses/examples:$plan9/bin"
export MANPATH="/usr/share/man:/usr/local/share/man:$h/man:$XDG_DOCUMENTS_HOME/roff/share/man:$plan9/man"
# $h/pebble-dev/pebble-sdk-4.5-linux64/bin:$h/dex2jar-2.0:
export roff="$h/doc/roff"
export GROFF="/usr/local/share/groff"
export MBLAZE="$XDG_CONFIG_HOME"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/default/config"
LYNX_CFG="$XDG_CONFIG_HOME/lynx/lynx.cfg"
LYNX_LSS="$XDG_CONFIG_HOME/lynx/lynx.lss"
# GS_LIB="$h/.local/share/ghostscript"
# GS_FONTPATH="$GS_LIB"
export GS_FONTPATH GS_LIB
# export QT_QPA_PLATFORM="$QT_QPA_PLATFORM=wayland-egl"
export QT_QPA_PLATFORMTHEME="qt5ct"
export CC="/usr/local/bin/tcc"
export STARDICT_DATA_DIR="$h/.local/share/stardict/dic/"
export BROWSER="firefox"
export INPUTRC="$XDG_CONFIG_HOME/inputrc"
export CDPATH=".:$h:$h/prj:$h/prj/app:"
export PF_INFO="ascii title os shell wm uptime pkgs palette"
export MANOPT="-L ru"
export PASSWORD_STORE_DIR="$h/.local/share/password-store"
export ZSHZ_CMD="q"
export SDCV_PAGER="less"
export DDGR_COLORS=xbdgxy
#export NNN_PLUG="v:imgview;o:dragdrop;t:treeview;f:preview-tui;r:fzz"
export NNN_PLUG="v:preview-tui;o:dragdrop"
export NNN_OPENER="$XDG_CONFIG_HOME/nnn/plug/nuke"
export NNN_FIFO=/tmp/nnn.fifo
export NNN_PREVIEWDIR="$XDG_CACHE_HOME"
#export NNN_TRASH=1
export NNN_OPTS="ea"
export NNN_FCOLORS=c1e200d0006033f7c6d6abc4
export sfeedpath="$XDG_DATA_HOME/sfeed"
export MMH="$XDG_DATA_HOME/mmh"
export {VISUAL,EDITOR}="nano -ASLx"
export DIARY_DIR="$h/doc/diary"
#COLORIZE LESS MANPAGER
#LESSOPEN="|lesspipe.sh %s"; export LESSOPEN
export LESS=-R
export LESS_TERMCAP_us=$'\E[3m'       # begin underline
export LESS_TERMCAP_ue=$'\E[23m'      # reset underline
export FZF_DEFAULT_COMMAND=${FZF_DEFAULT_COMMAND:-${FZF_CTRL_T_COMMAND="fd -H --type file . --exclude .git"}}